plugins { id 'com.android.application' }

android {
    namespace 'bw.co.swiftrun'
    compileSdk 34

    defaultConfig {
        applicationId 'bw.co.swiftrun'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
